### ISSUE TITLE
How to use the log program ?

### ISSUE THREAD

**Issue by limelect** [pjde/delphi-log#1]
How to use the log program ?

**Comment by pjde** [comment]
Forgot this was even on the repo.

It creates a small log window.
To add lines use LogEr(<error level>, <message to display>) 


There is a test program attached.

------ Original Message ------

**Comment by limelect** [comment]
One drastic improvement.
If you do not open the log screen any log are lost.
So add logs to string list and when log open add strings to log screen.
If log open do not add to string list but strait to log screen.
a few lines of code will improve

**Comment by pjde** [comment]
It was only posted so a colleague could upload it.

Modify to your hearts content.


Regards


Paul


------ Original Message ------
